backend:
  name: git-gateway
  branch: main # Ou a branch que você usará (ex: master)

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "posts"
    label: "Anotações"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{category}}/{{slug}}" # Salva em posts/categoria/slug.md
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Categoria", name: "category", widget: "select", options: ["Receitas", "Dicas para Casa", "Frases e Reflexões"] }
      - { label: "Resumo Curto (Opcional)", name: "excerpt", widget: "text", required: false }
      - { label: "Link Original (Opcional)", name: "original_url", widget: "string", required: false }
      - { label: "Conteúdo Principal", name: "body", widget: "markdown" }
      # Adicionar o layout automaticamente
      - { label: "Layout", name: "layout", widget: "hidden", default: "post.njk" }

# Configurações de internacionalização (opcional, mas bom ter)
locale: 'pt'

# Configurações do editor
editor:
  preview_style: "assets/css/style.css" # Para usar o CSS do blog na pré-visualização
